name: CI
on: 
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@master

    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1

    - name: MSBuild
      working-directory: src/WpfApp
      run: msbuild WpfApp.csproj
